---
- hosts: all
  connection: local
  become: true

  tasks:
  - name: build docker image using war file
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/docker

  - name: create image tag
    command: docker tag simple-devops-image jcfoster02/simple-devops-image

  - name: push image to DockerHub
    command: docker push jcfoster02/simple-devops-image

  - name: remove docker images from ansible server
    command: docker rmi simple-devops-image:lastest jcfoster02/simple-devops-image
    ignore_errors: yes
