---
- name: launch ec2 instance
  hosts: localhost      
  tasks:
   - name: ec2
     ec2:
       key_name: key3 
       instance_type: t2.micro
       image: ami-013f17f36f8b1fefb
       region: us-east-1
       count: 1
       wait: yes
       instance_tags:
         Name: WorkerNode-1    
